modLoader="javafml"
loaderVersion="[36,)"
license="MIT License"
issueTrackerURL="https://github.com/Mrthomas20121/FoodUpdate/issues"

[[mods]]
modId="food_update"
version="${file.jarVersion}"
displayName="Food Update"
displayURL="https://www.curseforge.com/minecraft/mc-mods/food_update"
#logoFile="tinkers_reforged_logo.png"
authors="Mrthomas20121"
description='''
My Idea for a Minecraft Food Update.
'''

[[dependencies.food_update]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.food_update]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_range}"
    ordering="NONE"
    side="BOTH"